format = """
  [](#ff79c6)\
$directory\
[](fg:#ff79c6 bg:#ffb86c)\
$git_branch\
$git_status\
[](fg:#ffb86c bg:#50fa7b)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#50fa7b bg:#8be9fd)\
$docker_context\
[](fg:#8be9fd bg:#6272a4)\
$time\
[](fg:#6272a4) \
"""

# Disable the blank line at the start of the prompt
add_newline = false

[username]
show_always = true
style_user = "bg:#bd93f9 fg:#282a36"
style_root = "bg:#bd93f9 fg:#282a36"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#bd93f9 fg:#282a36"
disabled = true # Disabled by default

[directory]
style = "bg:#ff79c6 fg:#282a36"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[c]
symbol = ""
style = "bg:#50fa7b fg:#282a36"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "bg:#8be9fd fg:#282a36"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = ""
style = "bg:#50fa7b fg:#282a36"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ""
style = "bg:#50fa7b fg:#282a36"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#ffb86c fg:#282a36"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#ffb86c fg:#282a36"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = ""
style = "bg:#50fa7b fg:#282a36"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#50fa7b fg:#282a36"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:#50fa7b fg:#282a36"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:#50fa7b fg:#282a36"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bg:#50fa7b fg:#282a36"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#50fa7b fg:#282a36"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥"
style = "bg:#50fa7b fg:#282a36"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#50fa7b fg:#282a36"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ""
style = "bg:#50fa7b fg:#282a36"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#6272a4 fg:#f8f8f2"
format = '[ $time ]($style)'
